/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Bottom: typeof import('./src/components/layout/bottom.vue')['default']
    Bottom2: typeof import('./src/components/layout/bottom2.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    Login: typeof import('./src/components/login/index.vue')['default']
    Main: typeof import('./src/components/layout/main.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('./src/components/layout/slider.vue')['default']
    Top: typeof import('./src/components/layout/top.vue')['default']
  }
}
