/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Bottom: typeof import('./src/components/layout/bottom.vue')['default']
    Bottom2: typeof import('./src/components/layout/bottom2.vue')['default']
    Card: typeof import('./src/components/home/card.vue')['default']
    Comment: typeof import('./src/components/home/comment.vue')['default']
    CommentItem: typeof import('./src/components/home/commentItem.vue')['default']
    DataView: typeof import('./src/components/home/dataView.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSearch: typeof import('element-plus/es')['ElSearch']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Header: typeof import('./src/components/layout/header.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    Login: typeof import('./src/components/login/index.vue')['default']
    Main: typeof import('./src/components/layout/main.vue')['default']
    MessageItem: typeof import('./src/components/layout/messageItem.vue')['default']
    MyCategory: typeof import('./src/components/layout/myCategory.vue')['default']
    MyHeader: typeof import('./src/components/layout/myHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('./src/components/layout/slider.vue')['default']
    Top: typeof import('./src/components/layout/top.vue')['default']
    VisitCount: typeof import('./src/components/home/visitCount.vue')['default']
  }
}
